---
abstract: 'Abuse the plack debug panel and keep your todo list in it.'
author:
  - 'Manni Heumann, C<< <cpan@lxxi.org> >>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::MockModule: '0'
  Test::Most: '0'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.11.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-Debug-Notepad
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Middleware::Debug::Notepad:
    file: lib/Plack/Middleware/Debug/Notepad.pm
    version: '0.06'
requires:
  Plack: '0'
  Plack::Middleware::Debug: '0'
  Text::Markdown: '0'
  Text::MicroTemplate: '0'
resources:
  bugtracker: https://github.com/mannih/Plack-Middleware-Debug-Notepad/issues
  homepage: https://github.com/mannih/Plack-Middleware-Debug-Notepad
  repository: git://github.com/mannih/Plack-Middleware-Debug-Notepad.git
version: '0.06'
x_contributors:
  - 'Manni Heumann <github@lxxi.org>'
